#ifndef PLCCFG_H_
#define PLCCFG_H_
// Auto command macro format: device_operate_level
// e.g. GAS_OPEN_CUTTING
//      GAS_OPEN_FIRST
//      LHC_FOLLOW_CUTTING
//      LHC_FOLLOW_FIRST
//      LHC_PROGRESSIVE_FIRST
//
//
enum PLC_CMD_ENUM {
  // 
  PLC_CMD_NONE = 0,
  // Gas Command
  GAS_OPEN_CUTTING = 100,
  GAS_OPEN_FIRST = 101,
  GAS_OPEN_SECOND = 102,
  GAS_OPEN_THIRD = 103,

  GAS_CLOSE_CUTTING = 104,
  GAS_CLOSE_FIRST = 105,
  GAS_CLOSE_SECOND = 106,
  GAS_CLOSE_THIRD = 107,

  GAS_PRESSURE_CUTTING = 108,
  GAS_PRESSURE_FIRST = 109,
  GAS_PRESSURE_SECOND = 110,
  GAS_PRESSURE_THIRD = 111,

  // Follower Command
  LHC_FOLLOW_CUTTING = 120,
  LHC_FOLLOW_FIRST = 121,
  LHC_FOLLOW_SECOND = 122,
  LHC_FOLLOW_THIRD = 123,

  LHC_PROGRESSIVE_FIRST = 124,
  LHC_PROGRESSIVE_SECOND = 125,
  LHC_PROGRESSIVE_THIRD = 126,

  LHC_LIFT = 127,

  // Laser Command
  LASER_ON = 140,
  LASER_OFF = 141,
  LASER_SHUTTER_ON = 142,
  LASER_SHUTTER_OFF = 143,

  // Delay Command
  DELAY_CUTTING_= 150,
  DELAY_FIRST = 151,
  DELAY_SECOND = 152,
  DELAY_THIRD = 153,

  DELAY_BLOW_CUTTING = 154,
  DELAY_BLOW_FIRST = 155,
  DELAY_BLOW_SECOND = 156,
  DELAY_BLOW_THIRD = 157,

};

#endif
