Import('env')
objs = []
objs.append(env.Object(["PlcCraft.cpp",
                        "JobSeeker.cpp", "JobLoader.cpp"],
                       CPPPATH=['/usr/include/linuxcnc', '.']))

Library('gcodebase', ['GCodeBase.cpp'])

Return('objs')
