Import('env')
objs = []
objs.append(env.Object(["PlcCraft.cpp", "GCodeBase.cpp",
                        "JobSeeker.cpp", "JobLoader.cpp"],
                       CPPPATH=['/usr/include/linuxcnc', '.']))

Return('objs')
